### ISSUE TITLE
Using weather oracle as dependency facing conflicting versions of MoveStdlib

### ISSUE THREAD

**Issue by KyrinCode** [MystenLabs/apps#42]
<img width="1109" alt="Screenshot 2024-05-10 at 15 06 22" src="https://github.com/MystenLabs/apps/assets/30864546/14e0ad09-3726-4a15-9bbd-78500f47bdde">

When I tried to add weather oracle as dependency, it requires the `rev` field to be exact 'a0e136a04'. However, even after I alter the `rev`, the compilation still failed in the latest sui client.

And does that mean that if my new project depends on any service, my sui-framework version has to be the same as the sui-framework version of that service? If so, this is crazy, since if multiple services are required as dependencies in my project, I cannot force them to be the same version.

**Comment by manolisliolios** [comment]
Hey @KyrinCode , you can get over this issue by adding `override=true` on your Sui dependency! 

For example:
```
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override=true }
```

I am closing the issue, feel free to re-open if there's anything unresolved after trying this!
