### ISSUE TITLE
Update Kiosk package manifest to new standard

### ISSUE THREAD

**Issue by thounyy** [MystenLabs/apps#50]
Update Move.lock for the Kiosk package on mainnet and testnet using 
```bash 
sui move manage-package --environment "$(sui client active-env)" \
  --network-id "$(sui client chain-identifier)" \
  --original-id 'PUBLISHED_ID' \
  --latest-id 'UPGRADED_ID' \
  --version-number 'VERSION'
```

Remove published-at from Move.toml.

Current format prevent from using a single package manifest for both mainnet and testnet.

**Comment by leecchh** [comment]
Thank you, addressed here https://github.com/MystenLabs/apps/pull/52

**Comment by thounyy** [comment]
bumping this @leecchh bc it hasn't been updated on the testnet branch and the address needs to be updated in Move.toml on /main

**Comment by thounyy** [comment]
done here #59 and here #60
